package com.circumgraph.storage.internal.processors;

import com.circumgraph.model.ArgumentUse;
import com.circumgraph.model.DirectiveUse;
import com.circumgraph.model.FieldDef;
import com.circumgraph.model.Location;
import com.circumgraph.model.processing.DirectiveUseProcessor;
import com.circumgraph.model.processing.ProcessingEncounter;
import com.circumgraph.model.validation.ValidationMessageType;
import com.circumgraph.storage.StorageModel;
import com.circumgraph.storage.internal.ValueProviders;

public class AutoGeneratedDirectiveProcessor
	implements DirectiveUseProcessor<FieldDef>
{
	private static final ValidationMessageType INVALID_ARGUMENTS = ValidationMessageType.error()
		.withCode("storage:@autoGenerated:invalid-arguments")
		.withMessage("@autoGenerated requires a provider")
		.build();

	private static final ValidationMessageType UNKNOWN_PROVIDER = ValidationMessageType.error()
		.withCode("storage:@autoGenerated:unknown-provider")
		.withMessage("The value provider `{{provider}}` is not available")
		.withArgument("provider")
		.build();

	private static final ValidationMessageType INVALID_PROVIDER = ValidationMessageType.error()
		.withCode("storage:@autoGenerated:invalid-provider")
		.withMessage("Value provider `{{provider}}` does not support the type `{{fieldType}}`")
		.withArgument("provider")
		.withArgument("fieldType")
		.build();

	private final ValueProviders valueProviders;

	public AutoGeneratedDirectiveProcessor(ValueProviders valueProviders)
	{
		this.valueProviders = valueProviders;
	}

	@Override
	public String getName()
	{
		return "autoGenerated";
	}

	@Override
	public Location getLocation()
	{
		return StorageModel.LOCATION;
	}

	@Override
	public Class<FieldDef> getContextType()
	{
		return FieldDef.class;
	}

	@Override
	public void process(
		ProcessingEncounter encounter,
		FieldDef location,
		DirectiveUse directive
	)
	{
		if(directive.getArguments().isEmpty()
			|| ! DirectiveUseProcessor.checkOnlyArguments(directive, "provider"))
		{
			encounter.report(INVALID_ARGUMENTS
				.toMessage()
				.withLocation(directive.getDefinedAt())
				.build()
			);

			return;
		}

		var provider = directive.getArgument("provider")
			.flatMap(ArgumentUse::getValueAsString);

		if(provider.isPresent())
		{
			// Using a provider - make sure its actually available
			var actualProvider = valueProviders.get(provider.get());
			if(! actualProvider.isPresent())
			{
				encounter.report(UNKNOWN_PROVIDER.toMessage()
					.withLocation(directive.getDefinedAt())
					.withArgument("provider", provider.get())
					.build()
				);
			}
			else
			{
				var instance = actualProvider.get();
				if(! location.getType().isAssignableFrom(instance.getType()))
				{
					encounter.report(INVALID_PROVIDER.toMessage()
						.withLocation(directive.getDefinedAt())
						.withArgument("provider", provider.get())
						.withArgument("fieldType", location.getTypeName())
						.build()
					);
				}

				StorageModel.setDefaultProvider(location, instance);
				StorageModel.setFieldMutation(location, StorageModel.MutationType.NEVER);
			}
		}
		else
		{
			encounter.report(INVALID_ARGUMENTS.toMessage()
				.withLocation(directive.getDefinedAt())
				.build()
			);
		}
	}
}
