package com.circumgraph.storage.internal.serializers;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;

import java.io.IOException;

import com.circumgraph.storage.internal.AutoGeneratedIdValue;

import org.junit.jupiter.api.Test;

import se.l4.exobytes.streaming.Token;

public class IdValueSerializerTest
	extends ValueSerializerTest
{
	@Test
	public void testRead()
		throws IOException
	{
		var instance = new AutoGeneratedIdValueSerializer();

		var in = write(out -> {
			out.writeLong(100);
		});

		var value = instance.read(in);
		assertThat(value, is(new AutoGeneratedIdValue(100l)));
	}

	@Test
	public void testWrite()
		throws IOException
	{
		var instance = new AutoGeneratedIdValueSerializer();

		var in = write(out -> {
			instance.write(
				new AutoGeneratedIdValue(100l),
				out
			);
		});

		assertThat(in.next(), is(Token.VALUE));
		assertThat(in.readLong(), is(100l));
	}
}
