package com.circumgraph.storage.directives;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.util.Optional;

import com.circumgraph.model.DirectiveUse;
import com.circumgraph.model.FieldDef;
import com.circumgraph.model.Location;
import com.circumgraph.model.ModelValidationException;
import com.circumgraph.model.ObjectDef;
import com.circumgraph.model.ScalarDef;
import com.circumgraph.model.Schema;
import com.circumgraph.model.StructuredDef;
import com.circumgraph.model.validation.ValidationMessageLevel;
import com.circumgraph.storage.ModelTest;
import com.circumgraph.storage.StorageModel;

import org.junit.jupiter.api.Test;

public class AutoGeneratedDirectiveTest
	extends ModelTest
{
	@Test
	public void testInvalidArgumentsEmpty()
	{
		var e = assertThrows(ModelValidationException.class, () -> createModel(Schema.create()
			.addType(ObjectDef.create("Test")
				.addField(FieldDef.create("field")
					.withType(ScalarDef.STRING)
					.addDirective(DirectiveUse.create("autoGenerated")
						.withDefinedAt(Location.create("LOC1"))
						.build()
					)
					.build()
				)
				.build()
			)
			.build()
		));

		var msg = e.getIssues().getFirst();
		assertThat(msg.getLevel(), is(ValidationMessageLevel.ERROR));
		assertThat(msg.getLocation(), is(Location.create("LOC1")));
		assertThat(msg.getCode(), is("storage:@autoGenerated:invalid-arguments"));
		assertThat(msg.getArguments().isEmpty(), is(true));
		assertThat(msg.getMessage(), is("@autoGenerated requires a provider"));
	}

	@Test
	public void testInvalidArgumentsUnknown()
	{
		var e = assertThrows(ModelValidationException.class, () -> createModel(Schema.create()
			.addType(ObjectDef.create("Test")
				.addField(FieldDef.create("field")
					.withType(ScalarDef.STRING)
					.addDirective(DirectiveUse.create("autoGenerated")
						.withDefinedAt(Location.create("LOC1"))
						.addArgument("arg1", "")
						.build()
					)
					.build()
				)
				.build()
			)
			.build()
		));

		var msg = e.getIssues().getFirst();
		assertThat(msg.getLevel(), is(ValidationMessageLevel.ERROR));
		assertThat(msg.getLocation(), is(Location.create("LOC1")));
		assertThat(msg.getCode(), is("storage:@autoGenerated:invalid-arguments"));
		assertThat(msg.getArguments().isEmpty(), is(true));
		assertThat(msg.getMessage(), is("@autoGenerated requires a provider"));
	}

	@Test
	public void testUnknownProvider()
	{
		var e = assertThrows(ModelValidationException.class, () -> createModel(Schema.create()
			.addType(ObjectDef.create("Test")
				.addField(FieldDef.create("field")
					.withType(ScalarDef.STRING)
					.addDirective(DirectiveUse.create("autoGenerated")
						.withDefinedAt(Location.create("LOC1"))
						.addArgument("provider", "THIS_DOES_NOT_EXIST")
						.build()
					)
					.build()
				)
				.build()
			)
			.build()
		));

		var msg = e.getIssues().getFirst();
		assertThat(msg.getLevel(), is(ValidationMessageLevel.ERROR));
		assertThat(msg.getLocation(), is(Location.create("LOC1")));
		assertThat(msg.getCode(), is("storage:@autoGenerated:unknown-provider"));
		assertThat(msg.getArguments().get("provider"), is("THIS_DOES_NOT_EXIST"));
		assertThat(msg.getMessage(), is("The value provider `THIS_DOES_NOT_EXIST` is not available"));
	}

	@Test
	public void testInvalidProvider()
	{
		var e = assertThrows(ModelValidationException.class, () -> createModel(Schema.create()
			.addType(ObjectDef.create("Test")
				.addField(FieldDef.create("field")
					.withType(ScalarDef.STRING)
					.addDirective(DirectiveUse.create("autoGenerated")
						.withDefinedAt(Location.create("LOC1"))
						.addArgument("provider", "ID")
						.build()
					)
					.build()
				)
				.build()
			)
			.build()
		));

		var msg = e.getIssues().getFirst();
		assertThat(msg.getLevel(), is(ValidationMessageLevel.ERROR));
		assertThat(msg.getLocation(), is(Location.create("LOC1")));
		assertThat(msg.getCode(), is("storage:@autoGenerated:invalid-provider"));
		assertThat(msg.getArguments().get("provider"), is("ID"));
		assertThat(msg.getArguments().get("fieldType"), is("String"));
		assertThat(msg.getMessage(), is("Value provider `ID` does not support the type `String`"));
	}

	@Test
	public void testExistingProvider()
	{
		var model = createModel(Schema.create()
			.addType(ObjectDef.create("Test")
				.addField(FieldDef.create("field")
					.withType(ScalarDef.ID)
					.addDirective(DirectiveUse.create("autoGenerated")
						.withDefinedAt(Location.create("LOC1"))
						.addArgument("provider", "ID")
						.build()
					)
					.build()
				)
				.build()
			)
			.build()
		);

		var test = model.get("Test", StructuredDef.class).get();
		var field = test.getField("field").get();

		assertThat(
			field.getMetadata(StorageModel.FIELD_MUTATION),
			is(Optional.of(StorageModel.MutationType.NEVER))
		);
		/*
		assertThat(
			field.getMetadata(StorageModel.FIELD_DEFAULT_VALUE_PROVIDER),
			is(Optional.of(new GeneratedIdValueProvider(new SimpleLongIdGenerator())))
		);
		*/
	}
}
