name: CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'pom.xml'
      - '**/pom.xml'
      - '**/src/**'

jobs:
  build:
    name: CI

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: 16
        distribution: 'adopt'

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build
      run: mvn compile -B -ntp --file pom.xml
    - name: Test
      run: mvn test -B -ntp --file pom.xml

    - name: Upload to Codecov
      uses: codecov/codecov-action@v2
