name: CI

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build:
    name: CI

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
        distribution: 'adopt'

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build
      run: mvn compile -B --file pom.xml
    - name: Test
      run: mvn test -B --file pom.xml

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

    - name: Upload to Codecov
      uses: codecov/codecov-action@v2
