name: Publish

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/publish.yml'
      - 'pom.xml'
      - '**/pom.xml'
      - '**/src/**'

jobs:
  build:
    name: Publish

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: 16
        distribution: 'adopt'
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - uses: fregante/setup-git-user@v1
    - name: Install standard-version
      run: |
        npm install --global standard-version
    - name: Login to ghcr.io
      uses: docker/login-action@v1.8.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        logout: true

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build
      run: mvn compile -B --file pom.xml
    - name: Test
      run: mvn test -B --file pom.xml
    - name: Generate CHANGELOG, commit and tag for release
      run: |
        if git rev-parse v0.1.0 >/dev/null 2>&1
        then
          standard-version
        else
          standard-version --first-release
        fi
    - name: Package
      run: mvn package -B -Ddeploy -DskipTests --file pom.xml
    - name: Push to Git
      id: push
      run: |
        git push --follow-tags
        echo ::set-output name=version-tag::$(git describe --tags $(git rev-list --tags --max-count=1))
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.push.outputs.version-tag }}
        name: ${{ steps.push.outputs.version-tag }}
        body_path: CHANGELOG.md
        prerelease: false
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Upload to Codecov
      uses: codecov/codecov-action@v2
