name: Publish

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/publish.yml'
      - 'pom.xml'
      - '**/pom.xml'
      - '**/src/**'

jobs:
  build:
    name: Publish

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: 16
        distribution: 'adopt'
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Login to ghcr.io
      uses: docker/login-action@v1.12.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        logout: true

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build
      run: mvn compile -B -ntp --file pom.xml
    - name: Test
      run: mvn test -B -ntp --file pom.xml
    - name: Create new release
      uses: cycjimmy/semantic-release-action@v2
      id: semantic
      with:
        extra_plugins: |
          @semantic-release/git
          @semantic-release/changelog
          @semantic-release/exec
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload to Codecov
      uses: codecov/codecov-action@v2
