name: Publish

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/publish.yml'
      - 'pom.xml'
      - '**/pom.xml'
      - '**/src/**'

jobs:
  build:
    name: Publish

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
        distribution: 'adopt'
    - name: Login to ghcr.io
      uses: docker/login-action@v1.8.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        logout: true
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build
      run: mvn compile -B --file pom.xml
    - name: Test
      run: mvn test -B --file pom.xml
    - name: Package
      run: mvn package -B -Ddeploy -DskipTests -Dquarkus.container-image.tag=latest '-Dquarkus.jib.labels."org.opencontainers.image.revision"='$GITHUB_SHA --file pom.xml
    - name: Upload to Codecov
      uses: codecov/codecov-action@v2.0.2
